vagrant:
  url: 'https://dl.bintray.com/mitchellh/vagrant/vagrant_1.6.5_x86_64.deb'
  package: 'vagrant_1.6.5_x86_64.deb'

virtualbox:
  url: 'http://download.virtualbox.org/virtualbox/4.3.20/virtualbox-4.3_4.3.20-96996~Ubuntu~raring_amd64.deb'
  package: 'virtualbox-4.3_4.3.20-96996~Ubuntu~raring_amd64.deb'