- name: Install virtualbox dependency
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 600
  with_items:
    - python-apt

- name: Create download directory
  file:
    path: /var/download
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Download Virtualbox
  get_url: 
    url: "{{ virtualbox.url }}"
    dest: "/var/download/{{ virtualbox.package }}"

- name: Install Virtualbox
  command: "dpkg -i /var/download/{{ virtualbox.package }}"

# - name: Add virtualbox apt-key
#   apt_key:
#     url: https://www.virtualbox.org/download/oracle_vbox.asc
#     state: present
#     validate_certs: false
#
# - name: Add virtualbox apt repository
#   apt_repository:
#     repo: 'deb http://download.virtualbox.org/virtualbox/debian trusty contrib'
#     state: present
#     update_cache: yes
#
# - name: Install virtualbox
#   apt:
#     pkg: "{{ item }}"
#     state: latest
#     update_cache: yes
#   with_items:
#     - virtualbox-4.3
#     - dkms
