- name: Copy id_rsa
  copy: 
    src: id_rsa
    dest: '/home/{{ remote.user }}/.ssh/id_rsa'
    owner: '{{ remote.user }}'
    group: '{{ remote.group }}'
    mode: 0600

- name: Copy id_rsa.pub
  copy: 
    src: id_rsa.pub
    dest: '/home/{{ remote.user }}/.ssh/id_rsa.pub'
    owner: '{{ remote.user }}'
    group: '{{ remote.group }}'
